name: CI Api Java

on:
  push:
    branches:
      - dev
      - homolog
      - producao
  pull_request:
    branches:
      - dev
      - homolog
      - producao

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17 and Environment Variables
        run: |
          echo "USUARIODB=${{ secrets.USUARIODB }}" >> $GITHUB_ENV
          echo "SENHADB=${{ secrets.SENHADB }}" >> $GITHUB_ENV
          echo "BANCO_USUARIO=${{ secrets.USUARIODB }}" >> $GITHUB_ENV
          echo "BANCO_SENHA=${{ secrets.SENHADB }}" >> $GITHUB_ENV
          
          echo "USUARIODB=${{ secrets.USUARIODB }}"
          echo "SENHADB=${{ secrets.SENHADB }}"

        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build-DB
        run: docker-compose build

      - name: Create-DB
        run: docker-compose up -d

      - name: Run Tests
        run: |
          cd dev
          mvn test --file ./pom.xml

      - name: Build with Maven
        run: |
          cd dev
          mvn -B package --file ./pom.xml